plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hatadefteri.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.hatadefteri.app"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('hata-defteri.p12')
            storeType 'pkcs12'
            storePassword 'hatadefteri'
            keyAlias 'hatadefteri'
            keyPassword 'hatadefteri'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'androidx.core:core:1.13.1'
}
